// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC545c40mb_peaN4ezKrm6THzVEcD5OwOs',
    appId: '1:582342089171:web:4b5ca27a83bcca083bb726',
    messagingSenderId: '582342089171',
    projectId: 'project-69946',
    authDomain: 'project-69946.firebaseapp.com',
    storageBucket: 'project-69946.appspot.com',
    measurementId: 'G-SXJHY0EM24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1oZBvJFSY-MOK_6TGxEuq7twaMb2K6I8',
    appId: '1:582342089171:android:1f6250a2772ae76b3bb726',
    messagingSenderId: '582342089171',
    projectId: 'project-69946',
    storageBucket: 'project-69946.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi1SeVti74pO1ZJiwuG2oga0ESy6e35y8',
    appId: '1:582342089171:ios:ed71f8e288e305c43bb726',
    messagingSenderId: '582342089171',
    projectId: 'project-69946',
    storageBucket: 'project-69946.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi1SeVti74pO1ZJiwuG2oga0ESy6e35y8',
    appId: '1:582342089171:ios:ed71f8e288e305c43bb726',
    messagingSenderId: '582342089171',
    projectId: 'project-69946',
    storageBucket: 'project-69946.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC545c40mb_peaN4ezKrm6THzVEcD5OwOs',
    appId: '1:582342089171:web:117a05cfc582934a3bb726',
    messagingSenderId: '582342089171',
    projectId: 'project-69946',
    authDomain: 'project-69946.firebaseapp.com',
    storageBucket: 'project-69946.appspot.com',
    measurementId: 'G-BXWJY5BND0',
  );

}